language: php

matrix:
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update
  - composer require "laravel/framework:^6.0" --no-update
  - composer require "orchestra/testbench:^4.0" --no-update

install:
  - travis_retry composer update --prefer-source --no-interaction --no-suggest

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
